name: orchestrate
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: 3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Firebase Config
  firebase_core: 3.12.0
  firebase_auth: 5.5.0

  # Responsiveness & screenutil
  flutter_screenutil: 5.9.3

  # State Management
  provider: 6.1.2

  # OTP input field
  pinput: 5.0.1

  # Local storage
  shared_preferences: 2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: SF-Pro-Rounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Black.ttf
        - asset: assets/fonts/SF-Pro-Rounded-Light.ttf
        - asset: assets/fonts/SF-Pro-Rounded-Medium.ttf
        - asset: assets/fonts/SF-Pro-Rounded-SemiBold.ttf
        - asset: assets/fonts/SF-Pro-Rounded-Thin.ttf
        - asset: assets/fonts/SF-Pro-Rounded-Regular.ttf
